language: csharp
mono: none
dotnet: 3.1

services:
  - docker
  
before_install:
  # login to docker registries (dockerhub)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
 - dotnet restore
 #- docker build -t modulofacturacion .
 # build docker images
 # - docker rm ModuloFacturacion -f
 # - docker rmi modulofacturacion -f
  
  
  # deploy:
   #provider: script
   #script:
    # push to dockerhub
    # docker push modulofacturacion;
   # branch: master
