language: csharp
mono: none
dotnet: 2.1.502
os: 
  - windows

services:
  - docker
  
before_install:
  # login to docker registries (dockerhub)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
 - dotnet restore
 - docker build -t modulofacturacion . 
