language: csharp
mono: none
dotnet: 3.1

services:
  - docker
  
before_install:
  - docker build -t modulofacturacion .
 
 script:
  - dotnet build
  - dotnet test UnitTestProject/UnitTestProject.csproj
