language: csharp
mono: none
dotnet: 3.1

services:
  - docker
  
before_install:
  - docker run -v ${PWD}:/app --workdir /app microsoft/dotnet:3.1-sdk dotnet new mvc --auth Individual
  - docker build -t modulofacturacion .
