language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 3.1

install:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1

services:
  - docker
  
before_install:
  - docker run -v ${PWD}:/app --workdir /app microsoft/dotnet:3.1-sdk dotnet new mvc --auth Individual
  - docker build -t modulofacturacion .
